[package]
name = "rtstore"
version = "0.1.0"
edition = "2021"


[dependencies]
nix = "0.22"
tonic = "0.6.2"
bytes = "1"
async-trait = "0.1.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.30"
tempfile = "3.3.0"
tokio = { version = "1.17.0", features = ["full"] }
prost = "0.9"
# Only necessary if using Protobuf well-known types:
prost-types = "0.9"
log = "0.4.16"
arrow = { version = "10.0", features = ["prettyprint"] }
parquet = { version = "12.0", features = ["arrow"] }
pretty_env_logger = "0.4.0"
uselog-rs = "0.3.0"
bincode = "1.1.4"
clap = { version = "3.1.8", features = ["derive"] }


[[bin]]
name = "rtstore"
path = "src/cmd/rtstore.rs"


[build-dependencies]
tonic-build = "0.6.2"
